### ISSUE TITLE
Migrate usage guide from README to dedicated snowplow/snowplow wiki page

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-python-analytics-sdk#12]

**Comment by chuwy** [comment]
Page already exists: https://github.com/snowplow/snowplow/wiki/Python-Analytics-SDK. In this commit I just deleted README section.

**Comment by chuwy** [comment]
@alexanderdean could you please check now README and both pages linked there?

**Comment by alexanderdean** [comment]
Thanks @chuwy - remove this section as it is duplicated from the setup guide:

https://github.com/snowplow/snowplow/wiki/Python-Analytics-SDK#installation
