### ISSUE TITLE
Migrate setup guide from README to dedicated snowplow/snowplow wiki page

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-python-analytics-sdk#13]

**Comment by chuwy** [comment]
Do we really want one-liner `pip install snowplow_analytics_sdk` has dedicated wiki page?

**Comment by alexanderdean** [comment]
Yes please! Keep things consistent...

**Comment by chuwy** [comment]
Created wiki page: https://github.com/snowplow/snowplow/wiki/Python-Analytics-SDK-setup#setup
