### ISSUE TITLE
Block until run manifests table in created state

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-python-analytics-sdk#20]
`table.meta.client.get_waiter('table_exists').wait(TableName='users')`

Otherwise we can end up in situation when client tries to add item to table that in `CREATING` state.

There's workaround for it, but would be nice to have as default behavior.

**Comment by alexanderdean** [comment]
What milestone should this go into @chuwy ?

**Comment by chuwy** [comment]
@alexanderdean I think 0.3.0 is fine. But if there's no plans for 0.3.0 yet, we can publish 0.2.1. Technically this is not a feature or behavior change and can be considered as bugfix.

**Comment by alexanderdean** [comment]
Let's treat as a bugfix then
