### ISSUE TITLE
Use standard regular expression for schema URIs

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-python-analytics-sdk#24]
Companion to https://github.com/snowplow/snowplow-scala-analytics-sdk/issues/22

Python SDK has same bug with hyphens in schema names and non-sense SchemaVer.

**Comment by alexanderdean** [comment]
Ouch good catch, let's get this into a patch release ASAP...

**Comment by chuwy** [comment]
I actually suspect this can have something to do with Spark job we're struggling with. So it definitely should be released as patch-release.
